#
# Twitter - webservice 
#
web:
  build: web
  ports:
    - "4000:4000"
  environment: 
    REDIS_HOST: redis
  links: 
    - redis
#
# Twitter - workerservice
#
worker:
  build: worker
  environment: 
    REDIS_HOST: redis
  links: 
    - redis

# Redis
redis:
  image: redis


